version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t webdpro-app .
      - docker tag webdpro-app:latest $ECR_REPO_URL:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO_URL:latest
      - echo Updating ECS service to force new deployment...
      - aws ecs update-service --cluster webdpro-cluster --service webdpro-service --force-new-deployment
